//音乐资源
var myMusics = new Array(
//{src:"yy/.mp3",title:""},
{src:"yy/云朵-化风行万里.mp3",title:"云朵-化风行万里"},
{src:"yy/郑秀文-信者得爱(feat. MC仁).mp3",title:"郑秀文-信者得爱(feat. MC仁)"},
{src:"yy/吴采乐-罗刹海市.mp3",title:"吴采乐-罗刹海市"},
{src:"yy/周传雄-关不上的窗.mp3",title:"周传雄-关不上的窗"},
{src:"yy/云朵-我的楼兰.mp3",title:"云朵-我的楼兰"},
{src:"yy/小棉袄-我这一生(女版).mp3",title:"小棉袄-我这一生(女版)"},
{src:"yy/黄静美-爱财爱己(DJ Eva版).mp3",title:"黄静美-爱财爱己(DJ Eva版)"},
{src:"yy/曹艺馨-多年以后.mp3",title:"曹艺馨-多年以后"},
{src:"yy/阿悠悠-思念成霜(DJ沈念版).mp3",title:"阿悠悠-思念成霜(DJ沈念版)"},
{src:"MC水公主-疯狂爱爱爱(DJ版).mp3",title:"MC水公主-疯狂爱爱爱(DJ版)"},
{src:"yy/乔艳艳 - 小人物 (DJ沈念版).mp3",title:"乔艳艳 - 小人物 (DJ沈念版)"},
{src:"yy/张禾禾-逃之夭夭.mp3",title:"张禾禾-逃之夭夭"},
{src:"yy/黄静美-无人与我（DJ刘超版）.mp3",title:"黄静美-无人与我（DJ刘超版）"},
{src:"yy/小鬼阿-秋言不由衷.mp3",title:"小鬼阿-秋言不由衷"},
{src:"yy/黄静美-余生各自安好（DJ武圣雄版）.mp3",title:"黄静美-余生各自安好（DJ武圣雄版）"},
{src:"yy/AZ珍珍-眼泪爱上了心碎（DJ可乐版）.mp3",title:"AZ珍珍-眼泪爱上了心碎（DJ可乐版）"},
{src:"yy/AZ珍珍-一个人孤单.mp3",title:"AZ珍珍-一个人孤单"},
{src:"yy/AZ珍珍-一个人挺好（女声版）.mp3",title:"AZ珍珍-一个人挺好（女声版）"},
{src:"yy/云朵-我的楼兰（DJ版）.mp3",title:"云朵-我的楼兰（DJ版）"},
{src:"yy/文儿-九世轮回篇.mp3",title:"文儿-九世轮回篇"},
{src:"yy/文儿-无敌霸王枪（DJ版）.mp3",title:"文儿-无敌霸王枪（DJ版）"},
{src:"yy/易欣-无法证明(DJ Candy版).mp3",title:"易欣-无法证明(DJ Candy版)"},
{src:"yy/S.H.E-Super Star.mp3",title:"S.H.E-Super Star"},
{src:"yy/S.H.E-不想长大.mp3",title:"S.H.E-不想长大"},
{src:"yy/S.H.E-恋人未满.mp3",title:"S.H.E-恋人未满"},
{src:"yy/S.H.E-热带雨林.mp3",title:"S.H.E-热带雨林"},
{src:"yy/S.H.E-痛快.mp3",title:"S.H.E-痛快"},
{src:"yy/陈慧琳&郑中基-都是你的错.mp3",title:"陈慧琳&郑中基-都是你的错"},
{src:"yy/陈慧琳&周传雄-记事本(Live).mp3",title:"陈慧琳&周传雄-记事本(Live)"},
{src:"yy/陈慧琳-记事本.mp3",title:"陈慧琳-记事本"},
{src:"yy/陈慧琳-快乐情人.mp3",title:"陈慧琳-快乐情人"},
{src:"yy/陈慧琳-替换.mp3",title:"陈慧琳-替换"},
{src:"yy/陈慧琳-心不设防.mp3",title:"陈慧琳-心不设防"},
{src:"yy/孟庭苇-冬季到台北来看雨.mp3",title:"孟庭苇-冬季到台北来看雨"},
{src:"yy/孟庭苇-没有情人的情人节.mp3",title:"孟庭苇-没有情人的情人节"},
{src:"yy/梦涵-爱的故事上集.mp3",title:"梦涵-爱的故事上集"},
{src:"yy/郑秀文-独家试唱.mp3",title:"郑秀文-独家试唱"},
{src:"yy/郑秀文-女人本色.mp3",title:"郑秀文-女人本色"},
{src:"yy/周传雄-黄昏.mp3",title:"周传雄-黄昏"},
{src:"yy/王馨平-梦里是谁.mp3",title:"王馨平-梦里是谁"},
{src:"yy/王馨平-爱债几时还.mp3",title:"王馨平-爱债几时还"},
{src:"yy/蒋嘉莹-假如真的再有约会.mp3",title:"蒋嘉莹-假如真的再有约会"},
{src:"yy/何晶晶-重生.mp3",title:"何晶晶-重生"},
{src:"yy/马小玲、况天佑-爱在地球毁灭时（珍藏版）.mp3",title:"马小玲、况天佑-爱在地球毁灭时（珍藏版）"}
);